version: '3'
services:
  fooocus:
    container_name: fooocus
    image: konieshadow/fooocus-api
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - 8886:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  ollama:
    container_name: ollama
    image: ollama/ollama
    volumes:
      - /home/mohammadreza/Volumes/Ollama:/root/.ollama
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]